name: TallMountain Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: rakudo-star:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install project dependencies
        run: zef install --deps-only .

      - name: Run tests
        run: make test
