name: TallMountain Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install rakubrew
        run: |
          sudo curl -sSL https://rakubrew.org/install-on-perl.org | bash
          sudo source ~/.rakubrew/bin/rakubrew
          echo 'export PATH=$HOME/.rakubrew/bin:$PATH' >> $GITHUB_ENV

      - name: Install Raku and set default version
        run: |
          source ~/.rakubrew/bin/rakubrew
          rakubrew build moar # Installs MoarVM backend by default
          rakubrew switch moar

      - name: Install zef
        run: |
          source ~/.rakubrew/bin/rakubrew
          rakubrew download zef

      - name: Install project dependencies
        run: zef install --deps-only .

      - name: Run tests
        run: make test
