name: TallMountain Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: rakudo-star:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install project dependencies
        run: zef install --deps-only .

      - name: Run tests
        run: make test
