name: TallMountain Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Raku and dependencies
        run: |
          sudo apt update
          sudo apt install -y rakudo make git
          sudo git clone https://github.com/ugexe/zef.git
          cd zef
          sudo raku -I. bin/zef install .

      - name: Install project dependencies
        run: zef install --deps-only .

      - name: Run tests
        run: make test
